### ISSUE TITLE
Does not work on 1.21+

### ISSUE THREAD

**Issue by jack-schultz** [unilock/YepTwo#4]
On my 1.21.1 fabric server, every advancements and death fails to send the proper information to the proxy, it just errors.

**Comment by unilock** [comment]
What errors? The client? The server? The proxy? What's the error? You're going to have to be more specific than that...

**Comment by LevyWilson** [comment]
> What errors? The client? The server? The proxy? What's the error? You're going to have to be more specific than that...

@unilock I don't know if this is the same error, but I'm having a similar issue on my ATM10 server. I finally got around to installing that Neoforge version of the mod and the Velocity plugin again. When a death message or an achievement is fired, though, nothing appears in Discord and the Velocity terminal spits this out:

`[00:35:15 ERROR]: Couldn't pass PluginMessageEvent to yeplib 2.3.0
java.lang.IllegalArgumentException: namespace is not valid, must match: [a-z0-9/\-_]* got `yep
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435) ~[velocity-3.4.0-SNAPSHOT-458.jar:3.4.0-SNAPSHOT (git-1db8c8c6-b458)]
        at com.velocitypowered.api.proxy.messages.MinecraftChannelIdentifier.create(MinecraftChannelIdentifier.java:55) ~[velocity-3.4.0-SNAPSHOT-458.jar:3.4.0-SNAPSHOT (git-1db8c8c6-b458)]
        at com.velocitypowered.api.proxy.messages.MinecraftChannelIdentifier.from(MinecraftChannelIdentifier.java:82) ~[velocity-3.4.0-SNAPSHOT-458.jar:3.4.0-SNAPSHOT (git-1db8c8c6-b458)]
        at cc.unilock.yeplib.YepLib.onPluginMessage(YepLib.java:68) ~[?:?]
        at cc.unilock.yeplib.Lmbda$4.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.4.0-SNAPSHOT-458.jar:3.4.0-SNAPSHOT (git-1db8c8c6-b458)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[velocity-3.4.0-SNAPSHOT-458.jar:3.4.0-SNAPSHOT (git-1db8c8c6-b458)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:541) ~[velocity-3.4.0-SNAPSHOT-458.jar:3.4.0-SNAPSHOT (git-1db8c8c6-b458)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`

**Comment by LevyWilson** [comment]
An example from a death: `java.lang.IllegalArgumentException: namespace is not valid, must match: [a-z0-9/\-_]* got >yep
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435) ~[velocity-3.4.0-SNAPSHOT-458.jar:3.4.0-SNAPSHOT (git-1db8c8c6-b458)]
        at com.velocitypowered.api.proxy.messages.MinecraftChannelIdentifier.create(MinecraftChannelIdentifier.java:55) ~[velocity-3.4.0-SNAPSHOT-458.jar:3.4.0-SNAPSHOT (git-1db8c8c6-b458)]
        at com.velocitypowered.api.proxy.messages.MinecraftChannelIdentifier.from(MinecraftChannelIdentifier.java:82) ~[velocity-3.4.0-SNAPSHOT-458.jar:3.4.0-SNAPSHOT (git-1db8c8c6-b458)]
        at cc.unilock.yeplib.YepLib.onPluginMessage(YepLib.java:68) ~[?:?]
        at cc.unilock.yeplib.Lmbda$4.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.4.0-SNAPSHOT-458.jar:3.4.0-SNAPSHOT (git-1db8c8c6-b458)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[velocity-3.4.0-SNAPSHOT-458.jar:3.4.0-SNAPSHOT (git-1db8c8c6-b458)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:541) ~[velocity-3.4.0-SNAPSHOT-458.jar:3.4.0-SNAPSHOT (git-1db8c8c6-b458)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`

**Comment by jack-schultz** [comment]
Yes this is a very similar error to the one i had. Sorry i did not post any info, i did this as it was noted that 1.21 builds "might not work" so i assumed they were untested. Therefore simply testing them would likely replicate my issues or you already knew about the problem. Looking back i still should have provided something. I apologise. 

I get similar errors for things like deaths and achievements. Any functionality this mod adds is currently broken in 1.21.1. The data fails to be sent correctly to the proxy and fails to display in Discord.

**Comment by unilock** [comment]
Minecraft 1.20.5 changed how packets work quite drastically. You can't just shove a ByteBuf through a Connection anymore; everything needs a god-forsaken Codec. Seems that my way to work around that didn't quite work out. I'm not really sure what the best way to accomplish "plugin messaging" is from non-Bukkit backends now...

**Comment by jack-schultz** [comment]
I did know that the whole packet system had changed. Thats why i originally didnt include any info as i assumed it was because of that and you knew. Im not entirely certain but there are a couple other discord plugins. Maybe reach out to one of those devs? Not sure how i can help.

**Comment by unilock** [comment]
> Im not entirely certain but there are a couple other discord plugins.

The difference is they don't run on the proxy *and* support advancement and death messages :p

**Comment by jack-schultz** [comment]
Yeah, I've just been testing them and you are very correct. If i learn of anything ill let you know!

**Comment by OzTheM9** [comment]
Id love to see a fix for this, cause we use this mod on our servers and it would be great to use for 1.21.1

**Comment by ehrie** [comment]
Has a workaround for this issue been found?

**Comment by unilock** [comment]
I tried giving this a look again. Unfortunately I'm still not sure what the solution is. I might just copy whatever Bukkit does for plugin messaging... or just open a websocket on the Velocity side for backends to send messages to without having to mess with Minecraft packets at all. (although this solution may be more complicated if backends are on a different host than the proxy)

If you'd like, you could give these builds a shot (rename .zip to .jar):

[yeptwo-2.1.1+1.21.1+fabric.zip](https://github.com/user-attachments/files/23860346/yeptwo-2.1.1%2B1.21.1%2Bfabric.zip)
[yeptwo-2.1.1+1.21.1+neoforge.zip](https://github.com/user-attachments/files/23860347/yeptwo-2.1.1%2B1.21.1%2Bneoforge.zip)

<sub>(I don't even use Velocity anymore...)</sub>

**Comment by ehrie** [comment]
Those both work so whatever shot in the dark you took hit true. Thanks!

**Comment by unilock** [comment]
Fixed with [v2.1.1+1.21](https://github.com/unilock/YepTwo/releases/tag/2.1.1%2B1.21) apparently!
